import { BusinessProfile, QRCodeItem, CustomerFeedback } from '../types';

export const DEMO_BUSINESS: BusinessProfile = {
  id: 'biz_demo_cafe_101',
  ownerId: 'demo_owner_101',
  name: 'Artisan Roast & Bakery',
  ownerName: 'Alex Morgan',
  email: 'alex@artisanroast.demo',
  phone: '+1 (555) 234-5678',
  category: 'Café',
  address: '442 Market Street, San Francisco, CA',
  description: 'Specialty pour-over coffee, fresh sourdough croissants, and cozy workspace with patio seating.',
  logoUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=150&auto=format&fit=crop&q=80',
  googleReviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
  slug: 'artisan-roast-cafe',
  status: 'active',
  createdAt: '2026-07-01T08:00:00.000Z',
};

export const DEMO_QR_CODES: QRCodeItem[] = [
  {
    id: 'qr_demo_table_1',
    businessId: 'biz_demo_cafe_101',
    businessSlug: 'artisan-roast-cafe',
    name: 'Indoor Tables',
    location: 'Main Dining Room Table Tent',
    slug: 'indoor-tables',
    active: true,
    scanCount: 142,
    feedbackCount: 88,
    createdAt: '2026-07-01T09:00:00.000Z',
  },
  {
    id: 'qr_demo_counter_2',
    businessId: 'biz_demo_cafe_101',
    businessSlug: 'artisan-roast-cafe',
    name: 'Billing Counter',
    location: 'Front Cashier & POS Stand',
    slug: 'billing-counter',
    active: true,
    scanCount: 94,
    feedbackCount: 52,
    createdAt: '2026-07-05T10:30:00.000Z',
  },
  {
    id: 'qr_demo_patio_3',
    businessId: 'biz_demo_cafe_101',
    businessSlug: 'artisan-roast-cafe',
    name: 'Outdoor Patio',
    location: 'Patio Umbrella Table 4',
    slug: 'outdoor-patio',
    active: true,
    scanCount: 65,
    feedbackCount: 39,
    createdAt: '2026-07-10T14:15:00.000Z',
  },
  {
    id: 'qr_demo_takeaway_4',
    businessId: 'biz_demo_cafe_101',
    businessSlug: 'artisan-roast-cafe',
    name: 'Takeaway Cup Sticker',
    location: 'To-Go Bag and Cup Sleeve',
    slug: 'takeaway-sleeve',
    active: true,
    scanCount: 48,
    feedbackCount: 26,
    createdAt: '2026-07-15T11:00:00.000Z',
  },
];

export const DEMO_FEEDBACKS: CustomerFeedback[] = [
  {
    id: 'fb_demo_01',
    businessId: 'biz_demo_cafe_101',
    qrId: 'qr_demo_table_1',
    qrLocationName: 'Indoor Tables',
    rating: 5,
    selectedCategories: ['Food & Beverage: Excellent', 'Staff Behaviour: Very friendly', 'Ambience: Great music & lighting'],
    customerComment: 'The almond croissant was flaky and fresh, and the barista poured a great oat flat white.',
    privateFeedback: 'Great playlist today, perfect volume level for working.',
    customerName: 'Sarah K.',
    selectedDraft: 'Had a wonderful visit to Artisan Roast & Bakery! The almond croissant was flaky and fresh, and the barista poured a great oat flat white. The staff were very friendly and the ambience was lovely.',
    googleReviewClicked: true,
    createdAt: '2026-08-20T18:45:00.000Z',
  },
  {
    id: 'fb_demo_02',
    businessId: 'biz_demo_cafe_101',
    qrId: 'qr_demo_counter_2',
    qrLocationName: 'Billing Counter',
    rating: 5,
    selectedCategories: ['Service Speed: Very fast', 'Staff Behaviour: Very friendly', 'Value for Money: Good'],
    customerComment: 'Super quick morning coffee pickup before work. Cashier greeted with a smile.',
    customerName: 'Marcus T.',
    selectedDraft: 'Super quick morning coffee pickup before work. Staff greeted with a smile and the service was fast. Great overall value at Artisan Roast & Bakery!',
    googleReviewClicked: true,
    createdAt: '2026-08-20T16:10:00.000Z',
  },
  {
    id: 'fb_demo_03',
    businessId: 'biz_demo_cafe_101',
    qrId: 'qr_demo_table_1',
    qrLocationName: 'Indoor Tables',
    rating: 4,
    selectedCategories: ['Food & Beverage: Good', 'Cleanliness: Spotless', 'Service Speed: Average'],
    customerComment: 'Coffee was delicious and seating area was super clean. Waited around 10 minutes for pour-over.',
    customerName: 'Elena R.',
    selectedDraft: 'Visited Artisan Roast & Bakery. The coffee was delicious and the seating area was spotless. Service speed was average with a slight wait for pour-overs, but worth the visit.',
    googleReviewClicked: false,
    createdAt: '2026-08-19T21:30:00.000Z',
  },
  {
    id: 'fb_demo_04',
    businessId: 'biz_demo_cafe_101',
    qrId: 'qr_demo_patio_3',
    qrLocationName: 'Outdoor Patio',
    rating: 5,
    selectedCategories: ['Ambience: Relaxing outdoor vibe', 'Food & Beverage: Excellent', 'Staff Behaviour: Very friendly'],
    customerComment: 'Loved sitting out on the sunny patio with our dog. They even brought out a water bowl.',
    customerName: 'David & Mia',
    selectedDraft: 'Loved our afternoon at Artisan Roast & Bakery! The sunny patio was relaxing and dog-friendly, and the drinks were top notch. Friendly staff made us feel right at home.',
    googleReviewClicked: true,
    createdAt: '2026-08-19T19:00:00.000Z',
  },
  {
    id: 'fb_demo_05',
    businessId: 'biz_demo_cafe_101',
    qrId: 'qr_demo_takeaway_4',
    qrLocationName: 'Takeaway Cup Sticker',
    rating: 3,
    selectedCategories: ['Service Speed: Slow', 'Food & Beverage: Good', 'Value for Money: Could be better'],
    customerComment: 'Coffee tasted great as usual, but line moved slowly during peak 8:30am rush.',
    privateFeedback: 'Consider adding a dedicated pickup line for mobile orders.',
    customerName: 'Jason P.',
    selectedDraft: 'Visited Artisan Roast & Bakery for takeaway coffee. The coffee tasted good, but service speed was slow during peak morning rush.',
    googleReviewClicked: false,
    createdAt: '2026-08-18T15:20:00.000Z',
  },
  {
    id: 'fb_demo_06',
    businessId: 'biz_demo_cafe_101',
    qrId: 'qr_demo_counter_2',
    qrLocationName: 'Billing Counter',
    rating: 5,
    selectedCategories: ['Food & Beverage: Excellent', 'Staff Behaviour: Very friendly', 'Cleanliness: Spotless'],
    customerComment: 'Best cold brew in the neighborhood. Baristas always remember my regular order.',
    customerName: 'Chloe M.',
    selectedDraft: 'Best cold brew in the neighborhood! The baristas at Artisan Roast & Bakery are always welcoming and attentive, and the café is sparkling clean.',
    googleReviewClicked: true,
    createdAt: '2026-08-17T17:40:00.000Z',
  },
  {
    id: 'fb_demo_07',
    businessId: 'biz_demo_cafe_101',
    qrId: 'qr_demo_patio_3',
    qrLocationName: 'Outdoor Patio',
    rating: 2,
    selectedCategories: ['Cleanliness: Needs attention', 'Service Speed: Slow'],
    customerComment: 'Outdoor table had crumbs from previous guest and took 15 minutes to clear.',
    privateFeedback: 'Staff seemed busy inside and neglected the patio area around 2pm.',
    customerName: 'Anonymous',
    selectedDraft: 'Honest feedback for Artisan Roast & Bakery: Outdoor patio table needed cleaning and service was quite delayed during my visit.',
    googleReviewClicked: false,
    createdAt: '2026-08-16T22:15:00.000Z',
  },
];
